Rails.application.routes.draw do
  resources :blogs do
    resources :posts do
      resources :comments
    end
  end
  get 'email/remind'
  post 'email/remind'
  get 'friendship/create/:screen_name' , to: 'friendship#create'
  post 'friendship/create/:screen_name' , to: 'friendship#create'
  get 'friendship/accept/:screen_name', to: 'friendship#accept'
  get 'friendship/decline/:screen_name', to: 'friendship#decline'
  get 'friendship/cancel/:screen_name', to: 'friendship#cancel'
  get 'friendship/delete/:screen_name', to: 'friendship#delete'
  post 'friendship/accept/:screen_name', to: 'friendship#accept'
  post 'friendship/decline/:screen_name', to: 'friendship#decline'
  post 'friendship/cancel/:screen_name', to: 'friendship#cancel'
  post 'friendship/delete/:screen_name', to: 'friendship#delete'
  get 'email/correspond/:screen_name' , to: 'email#correspond'
  post 'email/correspond/:screen_name' , to: 'email#correspond'
  get 'avatar/index'
  get 'avatar/upload'
  post 'avatar/upload'
  get 'avatar/delete'
  get '/' , to: 'site#index'
  get 'community/index'
  get 'community/browse'
  get 'community/search'
  get 'faq/index' , to: 'user#index'
  get 'faq/edit'
  post 'faq/edit'
  get 'spec/index'
  get 'spec/edit'
  post 'spec/edit'
  get 'profile/index'
  get 'profile/:screen_name' , to: 'profile#show'
  get 'profile/show'
  get 'user' => 'user#index'
  get 'user/index'
  get 'user/register'
  post 'user/register'
  get 'user/login'
  post 'user/login'
  get 'user/logout'
  get 'user/edit'
  post 'user/edit'
  get 'site/index'
  get 'site/about'
  get 'site/help'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
