Rails.application.routes.draw do
  get '/' , to: 'site#index'
  get 'community/index'
  get 'community/browse'
  get 'community/search'
  get 'faq/index' , to: 'user#index'
  get 'faq/edit'
  post 'faq/edit'
  get 'spec/index'
  get 'spec/edit'
  post 'spec/edit'
  get 'profile/index'
  get 'profile/:screen_name' , to: 'profile#show'
  get 'profile/show'
  get 'user' => 'user#index'
  get 'user/index'
  get 'user/register'
  post 'user/register'
  get 'user/login'
  post 'user/login'
  get 'user/logout'
  get 'user/edit'
  post 'user/edit'
  get 'site/index'
  get 'site/about'
  get 'site/help'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end
